language: node_js
node_js:
  - 12

branches:
  only:
  - main

services:
  - docker

script:
  - docker --version
  # Build API
  - docker build -t njyjn/udagram-api udagram-api/
  # Build Feed
  - docker build -t njyjn/udagram-feed udagram-feed/
  # Build Frontend
  - docker build -t njyjn/udagram-frontend udagram-frontend/
  # Build Users
  - docker build -t njyjn/udagram-users udagram-users/

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image push njyjn/udagram-api
  - docker image push njyjn/udagram-feed
  - docker image push njyjn/udagram-frontend
  - docker image push njyjn/udagram-users
